name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort poetry

    - name: Run black
      run: black .

    - name: Commit changes made by black
      run: |
        git diff --exit-code || (git commit -am "Code formatted with black" && git push)


    - name: Run flake8
      run: flake8

    - name: Run isort
      run: isort --check-only

    - name: Install interrogate
      run: pip install interrogate

    - name: Run interrogate
      run: interrogate -c pyproject.toml

    - name: Generate and save badge
      run: interrogate -c pyproject.toml --generate-badge interrogate_badge.svg

  build-and-publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'

    - name: Install poetry
      run: pip install poetry

    - name: Build and publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish --build

    - name: Push badge to master
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add interrogate_badge.svg
        git commit -m "Update documentation coverage badge"
        git push
